[package]
name = "tdt"
version = "0.1.0"
edition = "2021"

[dependencies]
home = "0.5"
anyhow = "1.0"
chrono = "0.4"
regex = "1.10"
colored = "2.1"
bitflags = "2.6"

[dependencies.clap]
version = "4.5"
features = ["derive", "unicode"]
