[package]
name = "todotxt"
version = "0.3.1"
edition = "2021"

[[bin]]
name = "tdt"
path = "src/main.rs"

[dependencies]
home = "0.5"
chrono = "0.4"
regex = "1.11.0"
colored = "2.1"
bitflags = "2.6"

[dependencies.clap]
version = "4.5.20"
features = ["derive", "unicode"]
